dist: bionic
language: java
jdk:
  - openjdk11

before_install:
 - chmod +x gradlew gradle/wrapper/gradle-wrapper.jar

install: 
- gradle wrapper
- ./gradlew compileJava

script: ./gradlew check jacocoTestReport javadoc

after_failure:
- cat build/test-results/test/*.xml
